### ISSUE TITLE
Wondering if the framework allows for loading of Prisoners (for transport)

### ISSUE THREAD

**Issue by NyarlathotepZERO** [SmashPhil/Vehicle-Framework#101]
**Is your feature request related to a problem? Please describe.**
I had a mission which asked me to raid a 'hideout' and capture a pawn dead or alive. After hitting the target with a tranquilizer dart, I was not able to load him onto the vehicle in any way whatsoever. 

**Describe the solution you'd like**
It would be terrific if the framework would allow for loading of prisoners in some way. Perhaps a temporary shackle whilst transporting. I have noticed that drop pods that eject the pawns for the 'please look after this prisoner for a few days' mission seem to tranq the prisoners prior, so they are unconscious on arrival. Perhaps manually loading onto them onto vehicles could do something similar based on certain conditions?

**Describe alternatives you've considered**
--

**Additional context**
--

**New Content**
Not sure if this is already a (planned?) feature but would be terrific if it was at all possible (and not too difficult) to implement.

**Comment by SmashPhil** [comment]
added as of v1.5.1368
