### ISSUE TITLE
Starting caravan with vehicle behind automatic door doesn't work

### ISSUE THREAD

**Issue by Reithan** [SmashPhil/Vehicle-Framework#105]
**Describe the bug**
My vehicle is stored in a garage behind an automatic garage door, but when I try to send a vehicle caravan it says 'The chosen exit location (X) is inaccessible'

**To Reproduce**
1. Put vehicle in room with automatic garage door
2. Try to form vehicle caravan
3. "The chosen exit location (X) is inaccessible"

**Screenshots**
![image](https://github.com/SmashPhil/Vehicle-Framework/assets/7475701/5d84feab-c5c6-480c-88ba-9e1fccbc2e68)
![image](https://github.com/SmashPhil/Vehicle-Framework/assets/7475701/f9db7e26-a096-46d7-ab3f-3419dc595037)

**Comment by Reithan** [comment]
I may be misunderstanding the explanation of the door. I understood that the door would automatically open/close when vehicles pass through, but it seems like it's just 'remote controllable' by the play, but still needs to be manually opened/closed?

**Comment by SmashPhil** [comment]
Yes, garage doors are not automatic. They still require input from the player.
