### ISSUE TITLE
Assigning Pawns to Vehicle with More than 15 Pawns Broken

### ISSUE THREAD

**Issue by Reithan** [SmashPhil/Vehicle-Framework#108]
**Describe the bug**
The "Assign Pawns" dialog with starting a vehicle caravan doesn't display all pawns if you have over 15 (some are cut off)

**To Reproduce**
1. Get more than 15 pawns
2. Star a vehicle caravan on the map
3. Select a vehicle
4. Colonist list is cut off and you can't select the colonists that aren't visible

**Screenshots**
![image](https://github.com/SmashPhil/Vehicle-Framework/assets/7475701/afb2d1d1-bf2f-45dd-9be1-13d6ead96649)
![image](https://github.com/SmashPhil/Vehicle-Framework/assets/7475701/79407f30-5616-4a93-8aae-8f44302c8a36)
![image](https://github.com/SmashPhil/Vehicle-Framework/assets/7475701/26a69eda-fe12-40fe-8270-91379c9f02e9)

**Comment by SmashPhil** [comment]
Yea I'm already tracking this one. I'm actually in the middle of fixing it right now.  It will be fixed in the next patch.  Thanks
