### ISSUE TITLE
Unable to path to a specific area while in a vehicle (not sure if it's a bug???)

### ISSUE THREAD

**Issue by Jatie1** [SmashPhil/Vehicle-Framework#116]
**Describe the bug**
Can't seem to path properly in an area that I think should be pathable. Wanted to make a garage in this area but can't seem to get my vehicle in here. It is the Big Rig vehicle from VVE. Tried using the garage gates too, it's a no go. Not sure if this even a bug tbh or I'm just doing something wrong.

**Screenshots**
![image](https://github.com/SmashPhil/Vehicle-Framework/assets/70575943/a65c3476-ea81-45f0-961d-e39e747ae36c)

https://github.com/SmashPhil/Vehicle-Framework/assets/70575943/1471b0f7-4677-4b6f-b456-9a0293b001cd

**Comment by katp32** [comment]
I am getting this issue as well. Vehicles are able to path into an area, but can't path out of it, even if every single wall is destroyed; the vehicle has to be deconstructed, wasting resources, as it cannot move anywhere.

**Comment by GodM0d3** [comment]
I think i had the same issue. But was able to fix it by saving and reloading the game (no complete restart, just a reload)

**Comment by SmashPhil** [comment]
Duplicate report, I already have a few on the discord.  There will be a fix in the next patch
