### ISSUE TITLE
Colonist doesn't rest on a vehicle

### ISSUE THREAD

**Issue by Fritcher36** [SmashPhil/Vehicle-Framework#117]
**Describe the bug**
I loaded a pawn on a Prowler and sent her with a caravan to trade. She doesn't seem to rest even if forced to, regardless of if she is inside the vehicle or transferred to "on foot" tab. Foot caravans without vehicles rest just all right.

**To Reproduce**
1. Start a caravan with a pawn
2. Wait until the night
3. See that pawn doesn't rest and continues to ride
4. Force a stop
5. See that pawn still doesn't rest even though the caravan is stopped

**Comment by xaqbr** [comment]
Still happening.

My colonist just immediately collapsed from exhaustion upon exiting a vehicle because their sleep was at 0%.
