### ISSUE TITLE
Big Rig can't cross river or marsh, even with bridge

### ISSUE THREAD

**Issue by VolcanicMedusa** [SmashPhil/Vehicle-Framework#120]
Hello, excellent mod btw!

Small bug I encountered, Oskar directed me to post it here.

While on my map, I'm not able get the Big Rig to cross the river or marshes on the map
- The right click message has the error "Big Rig cannot reach this area"
- Building a stone bridge doesn't help
- No issues with the highwayman, the bulldog, or the badger
- I know the Big Rig is heavier than the highwayman, and not tracked like the other two, but shouldn't it be able to cross once a bridge is built?
- I took a look through the defs folder, but didn't find anything relevant, so I'm not sure if this is an intentional design element or a bug.

Thanks for the help!

**Comment by SmashPhil** [comment]
No, vehicles allow path configurations by the modder and it was a deliberate choice for only combat vehicles to cross shallow water in Vanilla Expanded Vehicles.  You'll have to take it up with the author of that mod if you think this is unreasonable.
