### ISSUE TITLE
Aerial vehicle caravan disappear on landing

### ISSUE THREAD

**Issue by gogochlwns** [SmashPhil/Vehicle-Framework#127]
There seems to be a bug when dispatching an aerial vehicle to the destination. 
After reaching the destination and loading a new map, the vehicle is removed along with the pawn without specifying a landing point. When attempting a retry by reloading the game, it functions correctly.

**Comment by SmashPhil** [comment]
Please follow directions when reporting bugs, there is nothing I can do with the information you provided.  I need logs, steps to reproduce, and even screenshots or a video so I can see what exactly is going on.
