### ISSUE TITLE
[Compatibility] Crash to desktop on vehicle caravan entering map, settle location fails on vehicle caravan

### ISSUE THREAD

**Issue by RoyalFox2140** [SmashPhil/Vehicle-Framework#128]
**Describe the bug**
When a vehicle caravan either returns home to the colony map, raids a location (specifically tested via Real Ruins mod locations). When a vehicle caravan attempts to settle a colony map, it will cause an error unable to generate the map, and return to main menu.
When a vehicle caravan was attacked, I successfully generated the encounter, fought it off, and left without errors.

 Testing with a single colonist in a normal caravan, they are able to enter the same locations, settle new colonies, etc. 
 
 I believe it is a mod incompatibility, attached is two logs, one for the crash and one for the failed to generate a map. Among other mods, I have Caravan Activities framework, Real Ruins, Set up Camp, Star gates, and some misc. caravan tweak mods.

**To Reproduce**
1. Formed caravan with all of my colonists, 1 driver 1 gunner 4 passengers in an M113.
2. Went to trade with a settlement, successfully traded.
3. Attempted to enter new maps, create camp via Set up camp, settle location.
4. Crashes on attempting to enter map, returns to main menu upon generating new colony

**Screenshots**
My group after trading
![image](https://github.com/SmashPhil/Vehicle-Framework/assets/112293514/dc16347b-98aa-4d35-84fe-175bc452e9b4)
Upon attempting to settle with vehicle caravan
![image](https://github.com/SmashPhil/Vehicle-Framework/assets/112293514/c5f2c517-a303-44e0-969c-812a17d40828)

**Additional context**
Player-prev log contains the crash to desktop.
A hugslib log of the failing to generate the map and returning to main menu.

[Player-prev.log](https://github.com/SmashPhil/Vehicle-Framework/files/13871496/Player-prev.log)
https://gist.github.com/HugsLibRecordKeeper/f128a787f2eef103993d4f0233b3f3d8

**Comment by RoyalFox2140** [comment]
Ah, looking at https://docs.google.com/spreadsheets/d/1JRFSMzkXdFmg7wIJeR3W34KQZkRNBS_zQw4wdPoRPnc/edit#gid=0 shows me it's probably LTO Colony Groups. I'll disable it and test it out.

**Comment by RoyalFox2140** [comment]
It's not related to LTO Colony groups. New hugslib log. Tested on a dev quicktest world with the same M113 APC vehicle.
https://gist.github.com/HugsLibRecordKeeper/8b63a3e826ed89bc1a51243602c1341c

**Comment by SmashPhil** [comment]
It's hard to say, you have multiple exceptions related to startup sequence which could potentially cause gamebreaking issues.  If it's a mod compatibility issue (ie. you cannot reproduce this on VF + dependencies only) then the only way I'm going to take a look is if you can narrow down the culprit by doing a binary search (split mod list, check both halves, rinse repeat with the half that has the crash).  Your logs don't contain anything obvious and there's no way I have the time to load up your entire mod list.

If you can narrow down which mod causes it though, I'd be willing to look into it and potentially fix the issue.
