### ISSUE TITLE
Caravan doesn't work

### ISSUE THREAD

**Issue by Thyboss7** [SmashPhil/Vehicle-Framework#129]
**Describe the bug**
I'm trying to form a vehicle caravan with a flying vehicle(the smuggler from VE) and I have a runway, the plane is fueled. I go to add the plane and it says "Biome impassible for this vehicle." even though the vehicle I'm using flies.
**To Reproduce**
1. Form vehicle caravan
2. Click on 'Add vehicle (the checkmark)'
3. Scroll down to 'nothing'
4. See error "Biome impassible for this vehicle."

**Screenshots**
<img width="2240" alt="Screenshot 2024-01-16 at 10 53 09 AM" src="https://github.com/SmashPhil/Vehicle-Framework/assets/156825454/c1564417-7fbf-4a17-8806-20a090e31ab0">

**Additional context**
I'm using  Vanilla Vehicles expanded and VVE tier three

**Comment by RowanSkie** [comment]
How did you fix this?
