### ISSUE TITLE
Pawns don't stop panicking

### ISSUE THREAD

**Issue by dmitry-agapov** [SmashPhil/Vehicle-Framework#132]
The issue happens with Louie from [Vanilla Vehicles Expanded - Tier 3](/Vanilla-Expanded/VanillaVehiclesExpanded-Tier3).

I'm posting it here because i think that this is some edge case in the framework, rather than incorrect implementation of a specific vehicle:
1. Aside from this issue Louie works perfectly fine. 
2. ~I've looked into [definition of other similar vehicle](/Vanilla-Expanded/VanillaVehiclesExpanded/blob/main/1.4/Defs/VehicleDefs/Tier2/Mosquito/Mosquito_VehiclePawn.xml) (Mosquito from VVE) which doesn't have this issue. Compared it to [Louie's definition](/Vanilla-Expanded/VanillaVehiclesExpanded-Tier3/blob/main/1.4/Defs/VehicleDefs/Tier3/Louie/Louie_VehiclePawn.xml) and didn't see any big difference or anything weird.~ Upd: Upon further investigation i discovered that Mosquito is also affected by this issue.

Steps to reproduce:
1. Enter dev mode.
3. Activate "god mode".
4. Spawn Louie.
5. Select Louie.
6. Click "Explode component".
7. Choose any component.

What happens:
1. Louie catches fire.
2. Pawns will go to Louie and try to extinguish the fire.
3. After Louie is no longer on fire and is fully repaired the pawns will run around it in panic indefinitely. 

What should happen:
1. Louie catches fire.
2. Pawns will go to Louie and try to extinguish the fire.
3. After Louie is no longer on fire and is fully repaired the pawns will go about their business.

Somethimes pawns can't even begin to extinguish fire because of panic.
Drafting and moving them away from Louie isn't helping, they will go into panic mode every time they approach Louie.

**Comment by SmashPhil** [comment]
This is known to be an issue with Combat Extended, not Vehicle Framework.  In the future please include logs.
