### ISSUE TITLE
Mod settings break textbox contents alignment is some circumstances

### ISSUE THREAD

**Issue by abel1502** [SmashPhil/Vehicle-Framework#137]
In `Listing_Settings.FloatBox` and `Listing_Settings.IntBox`, `Text.CurTextFieldStyle.alignment` is overwritten but not reset. (`GUIState.Reset` does not, in fact, reset it without a preceeding `.Push`, as far as I understood it). This results in the setting leaking into other textboxes all over the game.

The easiest solution would be to add manual restoration code to the following locations:

https://github.com/SmashPhil/Vehicle-Framework/blob/4c92f6984cb77e9833fc87722d8fcb288b8508d3/Source/Vehicles/Graphics/Listing/Listing_Settings.cs#L216-L219

https://github.com/SmashPhil/Vehicle-Framework/blob/4c92f6984cb77e9833fc87722d8fcb288b8508d3/Source/Vehicles/Graphics/Listing/Listing_Settings.cs#L290-L293

The resulting code could look something like this:

```Csharp
TextAnchor savedAlignment = Text.CurTextFieldStyle.alignment;
Text.CurTextFieldStyle.alignment = TextAnchor.MiddleRight;
string buffer = value.ToString();
int /* or float */ valueBefore = value;
Widgets.TextFieldNumeric(rectRight, ref value, ref buffer, min, max); 
Text.CurTextFieldStyle.alignment = savedAlignment;
```

I have tested it on my instance by manually patching the DLL and can confirm that it did resolve the issue.

**Comment by abel1502** [comment]
Same as with my previous issue, no label nor assignee was set by default and I don't have access to setting those now. Tagging @SmashPhil because of this. This issue is a bug report

**Comment by SmashPhil** [comment]
GUIState is fairly new, so I may have missed a couple text settings that used to be manually reset in methods like these.  Adding alignment to it is simple enough.  One thing to note however, is that GUIState.Push _is_ called, just not in that method.  It's just that alignment isn't stored on the stack in GUIState.  Will be fixed in the next update
