### ISSUE TITLE
Vehicle cannot move to a certain area

### ISSUE THREAD

**Issue by Traveller23** [SmashPhil/Vehicle-Framework#138]
**Describe the bug**
There were some trees here that were preventing my car from reaching the clearing, and after I cut the trees down, the car still couldn't move past them.

**To Reproduce**

**Screenshots**
![Rim-World-Win64-HMa-Qs-Nds-ZU](https://github.com/SmashPhil/Vehicle-Framework/assets/117014547/f117161f-7128-42bc-ab5e-15dcf1068a00)

**Additional context**
Quit the game completely and open it again, then load the game, the problem will be gone.

Game verson: 1.4

**Comment by MidnightsFX** [comment]
I've also been experiencing this bug. Sometimes just saving, exiting and reloading from the main menu fixes it- or it will partially fix it, or not at all.

The first time I noticed this was being unable to path into a garage (with the nomad) using a 1x7 garage door. Could path to outside of the garage fine, couldn't go inside. Open/close garage door, still can't go in. Remove pawn from vehicle, leave garage open, save, quit to main menu/OS and then reload. Can path inside (much higher success with reloading from completely quitting the game).

It feels like a path caching issue but I'm no expert. I'm happy to provide any extra info that might help for debugging though!

**Comment by SmashPhil** [comment]
This should be fixed on 1.5.

**Comment by Traveller23** [comment]
There are still a lot of mods out there that haven't been updated to 1.5, so players are definitely going to be stuck on 1.4 for a month or two.
It would be great if you could fix the issue in 1.4 as well.

**Comment by MidnightsFX** [comment]
This was on 1.4, I'll test on 1.5 when I can, very excited to see if this is fixed!

**Comment by MidnightsFX** [comment]
This does seem to be fixed in 1.5, I haven't ran into it at all after a handful of vehicle trips. I'll keep trying, haven't tried all of the same vehicles. But I would have expected to run into it already 👍
