### ISSUE TITLE
Flying to another tile (selecting edge or center) and landing in a mountain = instantly vanished vehicle and colonists

### ISSUE THREAD

**Issue by Mjb141** [SmashPhil/Vehicle-Framework#144]
**Describe the bug**

If you fly to another tile in a helicopter (and presumably any other flying vehicle) and select land at edge or land at center, and that area is a mountain, your vehicle and everyone in it vanishes for good, and the tile you flew to vanishes (since your colonists are no longer in it).

**To Reproduce**
1. Build a helicopter
2. Load a driver
3. Fly to a tile that is 100% mountain (I've found mechanoid frigates are often 100% mountain)
4. Your vehicle and colonist will vanish, never to be seen again.

**Comment by Mjb141** [comment]
Worth adding to this. I often find this when I fly to an event (e.g. a quest) tile: 

![image](https://github.com/SmashPhil/Vehicle-Framework/assets/46346590/245c5292-1da3-4569-91f9-935176d06013)

A whole tile of mountain, nothing visible. If you land the helicopter explodes, all colonists immediately vanish, and the `Game Over` notification pops up on the right hand side. 

What causes this?

**Comment by Alili-Official** [comment]
same issue , clear all fog could fix it

**Comment by SmashPhil** [comment]
Fixed as of 1.5.1569
