### ISSUE TITLE
Anomaly issue. Error in rendering holding platform.

### ISSUE THREAD

**Issue by PlagueCtr** [SmashPhil/Vehicle-Framework#147]
**Describe the bug**
I have an issue with the DLC Anomaly's holding platforms in conjunction with the vehicle framework.

**To Reproduce**
Having both vehicle framework and Anomaly installed. Could it be a load order issue? I have no idea.
**Screenshots**
![image_2024-04-23_075713815](https://github.com/SmashPhil/Vehicle-Framework/assets/167874347/b973fb32-ebd2-458d-ae73-d7cce4461e76) - with vehicle framework.

**Additional context**
I have been playing Anomaly since its release. I had this issue until I discovered a Reddit thread discussing rendering issues with the holding platform (pawns being invisible). They all had removed the vehicle framework, and it was fixed; same for me. Perhaps the vehicle framework is conflicting with another mod, and these are just the symptoms? Using vehicle framework since 1.4 with no issues.

Hugslib log:
https://gist.github.com/HugsLibRecordKeeper/31f8087fc0744a03f3a639bbc4f6a281 - file is truncated, by the way.

**Comment by PlagueCtr** [comment]
![image_2024-04-23_081559140](https://github.com/SmashPhil/Vehicle-Framework/assets/167874347/208ccd7f-734a-499e-9430-07ae40018cad) - without vehicle framework.

**Comment by SmashPhil** [comment]
Fixed in 1.5.1587
