### ISSUE TITLE
Fuel Cost variable name shows up instead of its value while launching an airborne vehicle

### ISSUE THREAD

**Issue by Sawrz** [SmashPhil/Vehicle-Framework#148]
**Describe the bug**
When launching a vehicle that can fly, the fuel cost estimation only shows the variable's name.

**To Reproduce**
1. Minimal installation in my case: Vanilla Expanded Framework, Vehicle Framework, Vanilla Vehicles Expanded, Vanilla Vehicles Expanded Tier 3 (in a nutshell: everything that is needed to use Vanilla Expanded Vehicles.)
2. Board vehicle, e.g. Mosquito.
3. Launch and see the variable name instead of its value on the world map.

**Screenshots**
![screenshot2](https://github.com/SmashPhil/Vehicle-Framework/assets/9134364/6f385831-2e4f-44ea-9c03-bfbbdf37af44)

**Additional context**
In version 1.4, everything worked exceptionally well. Since 1.5 the issue exists. The error shows up in a normal game as well as in a DEV Quickstart. 

In case you need anything more, e.g. logs., let me know.

**Comment by SmashPhil** [comment]
It's fixed in the next update, I just haven't pushed it yet.
