### ISSUE TITLE
Pawns getting stuck while bringing items for upgrade

### ISSUE THREAD

**Issue by KentHaeger** [SmashPhil/Vehicle-Framework#149]
While testing my mod's vehicle upgrades, I discovered that pawns would attempt to bring entire stacks of items to the vehicle (rather than just the number requested by the upgrade), then get stuck in an endless job loop trying to deliver the excess items. The issue seems to be this line in Vehicles.WorkGiver_BringUpgradeMaterial.JobOnThing:

int countLeft = CountLeftToPack(vehicle, pawn, new ThingDefCount(thing.def, thing.stackCount));

which passes in the full stackCount of the first appropriate Thing that it finds, rather than the number the upgrade will actually accept.

**Comment by SmashPhil** [comment]
didn't realize you made a post, fixed a few months ago as per our conversation on discord.
