### ISSUE TITLE
Unable to send vehicle caravans with Geological Landforms installed

### ISSUE THREAD

**Issue by tiger8255** [SmashPhil/Vehicle-Framework#151]
Apologies if this bug needs to be fixed on Geological Landforms' end - wasn't sure who to report it to so I'm reporting it to both :)

**Describe the bug**
Attempting to send a vehicle caravan with Geological Landforms installed and active will lead to a message saying that the chosen exit location is inaccessible, even if it shouldn't be. The caravan will then refuse to form.

**To Reproduce**
1. Have Geological Landforms installed
2. Ensure a clear path from the vehicle to the edge of the map
3. Go to world map and form vehicle caravan as usual
4. Click accept
5. Caravan will refuse to form, claiming the map edge is inaccessible.

**Additional context**
Hugslib log, though it doesn't look like there's much of note here: https://gist.github.com/HugsLibRecordKeeper/6dc548e8cd8ebeca1c1d63ac0a3907ea

Removing Geological Landforms fixed the issue with no other changes made.

The map I was playing on was one with vanilla generation. Geological Landforms was added mid-save.

The only vehicle mods I'm using are Vanilla Vehicles Expanded and its Tier 3 submod. I ran into this issue with the Big Rig specifically and did not test other vehicles (though maybe I should have..)

**Comment by m00nl1ght-dev** [comment]
Unfortunately I could not replicate the issue using the steps you described. Caravan is formed as expected. So either the issue only happens on specifc maps, or one of your other mods is involved. Therefore please try to replicate the issue again with **only** Geological Landforms and the Vehicle mods + dependencies installed. If you get it to happen again, send the world seed + tile coordiantes so I can try to replicate it exactly.

**Comment by tiger8255** [comment]
> Unfortunately I could not replicate the issue using the steps you described. Caravan is formed as expected. So either the issue only happens on specifc maps, or one of your other mods is involved. Therefore please try to replicate the issue again with **only** Geological Landforms and the Vehicle mods + dependencies installed. If you get it to happen again, send the world seed + tile coordiantes so I can try to replicate it exactly.

Ah shit, sorry! I really should've tested it more. I'll see if I can figure anything more specific out.
In the meantime, the world seed is "stuffers" and the coordinates are 1.33°N 62.30°E.
I've got Realistic Planets Continued installed too (and will test to see if that affects it in a moment), but the settings for that are 45% coverage, normal sea level, slightly high rainfaill, slightly low temperature, and normal axial tilt.

**Comment by tiger8255** [comment]
Aha! I was able to recreate it using the same coordinates and map with only the involved mods (Vehicle Framework, VVE, VVE Tier 3, Geological Framework, and Realistic Planets Continued for the same world gen)

It works fine as-is, but due to map designer shenanigans the map in my save is only able to be entered on the north side. Placing rocks blocking all east, west, and south entrances on the fresh map allows me to reproduce the issue.

**Comment by tiger8255** [comment]
Alright, after further testing it seems like this only happens with the VVE Wisent and the VVE Tier 3 Big Rig, and only when north is the only available exit. It works fine if they can only go south, east, or west.

**Comment by tiger8255** [comment]
..and now it's working completely fine, and I cannot reproduce it. Not even in the original save. Weird.

There's a good possibility the problem was on my end the entire time. I don't know what it was and I don't know why it's working now, but.. I guess it's gone?

I'm terribly sorry for wasting your time with this!

**Comment by m00nl1ght-dev** [comment]
No worries, thanks for looking into it, the details may still be useful in case a similar issue is reported in the future.
