### ISSUE TITLE
Error log spam

### ISSUE THREAD

**Issue by SetiZhenya** [SmashPhil/Vehicle-Framework#152]
An error spam on a vehicle caravan

I haven't seen anyone else describe this problem but:
>create a caravan with any vehicle
>get error log spammed

complete error log: https://gist.github.com/HugsLibRecordKeeper/f82e9d01fe541df4dc6ffedd2bce073a

**Comment by SmashPhil** [comment]
Your exceptions are coming from Trade Price Fix, not from Vehicle Framework.  Apart from that patch not executing properly, and thus throwing further exceptions (spamming your logs), I can't see anything related to Vehicle Framework.

@SetiZhenya Please let me know if you're still having issues without that mod, or if it specifically goes away without Vehicle Framework.

**Comment by SetiZhenya** [comment]
thank you so much! its fixed!
