### ISSUE TITLE
Fuel fire re-igniting upon refueling vehicle

### ISSUE THREAD

**Issue by TomTheHand** [SmashPhil/Vehicle-Framework#157]
I am running the current Steam versions of Vehicle Framework, Vanilla Vehicles Expanded, and Vanilla Vehicles Expanded Tier 3. I'm still running Rimworld 1.4 for compatibility with some of my mods. If this problem is related to VVE rather than the framework itself, just let me know and I'll get in touch with them instead.

I have a Big Rig, from VVE Tier 3. It caught fire from an incendiary mortar shell fired by a mechanoid auto-mortar. I tried driving it out of the fire, and saw that it was trailing flames, so I realized that the fuel was on fire. It was carrying a variety of cargo, including several hundred units of chemfuel. After dealing with the mechanoids, my pawns fought the fire and eventually put it out, but not before all of the fuel in the vehicle's fuel tanks had burned up. I still had the chemfuel in the cargo area; I don't think any of it was consumed in the fire.

My pawns repaired the Big Rig, but I noticed that they weren't auto-refueling it, even though I had unloaded some chemfuel and they had used it to refuel my other vehicle. A day or two later, I had a pawn enter as a passenger and I clicked "Refuel from inventory". The fire immediately reignited. My pawns quickly put it out, and only two (out of 160) units of chemfuel in the tanks were lost. There was no further reignition.

It would appear that if a vehicle's fuel tank is on fire, and all of its fuel is consumed in the blaze, it will stop spawning flames but perhaps its "I'm on fire!" tag isn't getting cleared. I'm not sure if the chemfuel in the cargo area was a contributing factor, but it's possible.

Steps to reproduce:
Set a vehicle's fuel tank on fire.
Without allowing the vehicle to be destroyed, allow all of the fuel to burn up (perhaps by starting with low fuel).
Extinguish all flames.
Note that pawns aren't auto-refueling the vehicle, even when fuel is available.
Order a pawn to enter the vehicle, and click "Refuel from inventory"
Note that the vehicle bursts into flames again.

**Comment by SmashPhil** [comment]
You likely still had chemfuel puddles below your vehicle from it leaking.  You described the fuel as "burning up" but that's actually leaking onto the ground beneath your vehicle.  Your vehicle is not going to allow refuel jobs while it has an active leak, hence the jobs not being enabled for it.

As for the fire re-igniting, chemfuel puddles being flammable is a vanilla feature so you definitely didn't put out all the fires.  You might've had 1 or 2 tiny ones beneath the vehicle which re-ignited the chemfuel puddles that were also beneath your vehicle.

**Comment by TomTheHand** [comment]
Thanks for looking at this. It happened a couple of months ago, so it's no longer fresh in my mind, but it appears that you misunderstood me. The reignition occurred several days after the battle and the fire; it was _absolutely_ out. I killed all of the mechanoids and - again - spent multiple in-game days scavenging the map before digging into the issue with my fuel-less vehicle.

**Comment by SmashPhil** [comment]
The vehicle not accepting refueling after having a leak repaired was a bug reported to me recently and is fixed in the next patch.  That is a separate issue from chemfuel puddles spontaneously combusting, one that I am unable to reproduce. 

Logs were also not included with the post so I'm unable to check if it might be caused by another mod.  If you're still able to reproduce the issue on the current version, feel free to create another ticket.

**Comment by TomTheHand** [comment]
Thank you! Sorry about the lack of logs and the irreproducibility of the bug. I'll look forward to playing the next version and I'll test the issue if I can (and document it better if I encounter it).
