### ISSUE TITLE
Missing Label key in language xml

### ISSUE THREAD

**Issue by Gensando** [SmashPhil/Vehicle-Framework#159]
**Describe the bug**
The label key `VF_VehicleFuelCost` is missing from translation xml, so whenever u use flying vehicles it will display key name on the world map instead of the fuel cost.

**To Reproduce**
1. Construct any flying vehicle
2. Click "Launch" button
3. Mouse over any tile on world map
4. Look at tooltip under cursor, it should display `VF_VehicleFuelCost`

**Screenshots**
![image](https://github.com/SmashPhil/Vehicle-Framework/assets/34553011/1598198d-7d4d-4de5-ab29-d1d43e01542a)

**Comment by Gensando** [comment]
Sure, sry for disturbance then, just couldn't find the key on master except in code thus opened an issue :)

**Comment by SmashPhil** [comment]
Oh I don't push directly to master.  Pending changes are pushed to the _feature/unstable-testing_ branch.  Master is equivalent to the steam version, so only published builds.
