### ISSUE TITLE
Roads of the Rim patch method changed

### ISSUE THREAD

**Issue by delmain** [SmashPhil/Vehicle-Framework#163]
**Describe the bug**
The patch that Vehicle Framework has for Roads of the Rim needs to be updated. Mlie re-structured some code and the class name changed.

**To Reproduce**
1. Compile unstable-testing branch 
2. Observe RotR patch that was working fails

**Screenshots**
N/A

**Additional context**
I reported a bug with RotR that had to do with Regrowth:Core, and in the process of fixed that bug, they restructured a bunch of patch classes, so I feel bad about breaking this patch here.

The new method that needs to be patched is `"RoadsOfTheRim.HarmonyPatches.Alert_CaravanIdle_GetReport"`. I checked out master, changed this target in `Compatibility_RoadsOfTheRim.cs` and recompiled and the patch is working as expected. The only thing that changed is the class name.

Mlie's PR that has the changed class name: https://github.com/emipa606/RoadsOfTheRim/commit/f581b5f0bc877042851917ab2b1233e444a52efa#diff-0e6f27844778da8e546319cc24da1bfa232f149b27dbd487030ee1d4f22dc0f1

**Comment by SmashPhil** [comment]
Are you sure you were testing with unstable branch?  It's fixed on there already.  The patch hasn't been pushed out yet (I'm doing some testing now, along with 1 more bugfix) so it's not fixed on steam.  Master branch is also kept up to date with the steam version, which means it's not fixed on there either.

**Comment by SmashPhil** [comment]
Oh you're right, they changed the name again.  Alright, it's fixed in the next update.  Thanks!
