### ISSUE TITLE
Backport River Travel to 1.4

### ISSUE THREAD

**Issue by oliverrook** [SmashPhil/Vehicle-Framework#166]
**Is your feature request related to a problem? Please describe.**
I would very much like the river travel part of the mod backported to 1.4, as I still use that version due to certain mods and my active playthrough being on it. It doesn't appear to exist on the 1.4 version.

**Describe the solution you'd like**
I would like this feature backported, as I started this playthrough with it in mind, though I wasn't aware it was still being worked on. My settlement is landlocked and I started on a river for this exact reason.

**Describe alternatives you've considered**
I suppose it would be possible for me to do it myself if I looked into the 1.5 code for it, but it would take me significantly longer due to it being somebody else's code I am unfamiliar with. I am also not nearly as familiar with making Rimworld mods as other things.

**Additional context**
N/A

**New Content**
N/A

**Comment by SmashPhil** [comment]
Sorry, I won't be providing support for prior versions apart from major bugfixes.  If you want to use new features you'll have to update to the latest version.
