### ISSUE TITLE
Pawns unloading loaded cargo

### ISSUE THREAD

**Issue by oliverrook** [SmashPhil/Vehicle-Framework#167]
**Describe the bug**
I tell pawns to load cargo onto a vehicle, they begin to do so, but at some point a pawn or two come along and just immediately unload all of it onto the ground, and it's taken off the list. This occurs whether forming a caravan or using the load button and it occurs regardless of whether loading is still in progress.

**To Reproduce**
1. Have a bunch of pawns assigned to hauling (5 or more)
2. Attempt to load cargo (at least a few stacks of different items)
3. See error

**Screenshots**
![image](https://github.com/SmashPhil/Vehicle-Framework/assets/1887407/cae1fff2-d584-4c42-b1fd-d31c8318786c)

**Additional context**
I have pickup and haul, along with share the load installed. But neither should effect stuff already loaded into the vehicle being taken out.

**Comment by SmashPhil** [comment]
Sounds like your inventory got flagged for complete unloading.  This shouldn't happen for vehicles, but you can reset it by having the vehicle leave the map.  That'll set 'unload everything' back to false.
