### ISSUE TITLE
Vehicle Entry Points

### ISSUE THREAD

**Issue by oliverrook** [SmashPhil/Vehicle-Framework#168]
**Is your feature request related to a problem? Please describe.**
I tend to like to go for mountain based, which means the fact that a vehicle entering the map from any direction can be... problematic, as it can often spawn in a location that isn't mined out yet or isn't setup for vehicles.

**Describe the solution you'd like**
It would be great if, similar to to stuff like party spots or caravan hitching spots, if we could designate a location on the map where we'd like vehicles to enter. It doesn't necessarily have to be an object, just some manner of ability to do this would be amazing.

**Describe alternatives you've considered**
Perhaps simply a "zone" could also work, or even just the ability to have a vehicle enter the same location it exited.

**Additional Context**
While it is possible to setup mountain bases (not like full map mountain bases, but bases with a ton of blocked off space) for vehicles, it can be an immense hassle and it ultimately defeats the point of having a mountain base if you have to have holes in your defenses on any given side to account for vehicles entering.

**Comment by SmashPhil** [comment]
This functionality overlaps with the next patch's 'road area' feature.
