### ISSUE TITLE
UnityEngine.Texture2D at SmashTools/VideoSkipToNext - Intermittent Error on Startup

### ISSUE THREAD

**Issue by mcmookerson** [SmashPhil/Vehicle-Framework#171]
After the 2024-06-22 update to Vehicle Framework, I've been getting the following error from time to time on startup. I'll admit that it could be an incompatibility with another mod, but I only see this one referenced in the error log, and I don't change my modlist at all between when the error occurs and when it doesn't, or vice-versa.

Could not load UnityEngine.Texture2D at SmashTools/VideoSkipToNext in any active mod or in base resources.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Log.Error_Patch4 (string)
Verse.ContentFinder`1<UnityEngine.Texture2D>:Get (string,bool)
SmashTools.Animations.Dialog_AnimationEditor:.cctor ()
System.Runtime.CompilerServices.RuntimeHelpers:RunClassConstructor (System.RuntimeTypeHandle)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.StaticConstructorOnStartupUtility.CallAll_Patch2 ()
Verse.PlayDataLoader/<>c:<DoPlayLoad>b__4_4 ()
Verse.LongEventHandler:ExecuteToExecuteWhenFinished ()
Verse.LongEventHandler:UpdateCurrentAsynchronousEvent ()
Verse.LongEventHandler:LongEventsUpdate (bool&)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Root.Update_Patch1 (Verse.Root)
Verse.Root_Entry:Update ()

**Comment by SmashPhil** [comment]
ignore it, it's harmless.  It's related to the animation editor and is fixed in the next update

**Comment by mcmookerson** [comment]
Sounds good! Thanks, friend.
