### ISSUE TITLE
A stacktrace when a beetle corpse is immersed in an airplane #3

### ISSUE THREAD

**Issue by dians1s** [SmashPhil/Vehicle-Framework#172]
We were playing with a friend and during the exchange he loaded a bug into the plane, after that I can't interact with the plane and the pawn in it in any way. Please help me :d 
![баг](https://github.com/SmashPhil/Vehicle-Framework/assets/140249111/b1ba96fe-e9a4-45a3-98b4-77f5eefeecaf)

**Comment by SmashPhil** [comment]
Duplicate report, will be fixed in a future update
