### ISSUE TITLE
Player loses control over pawns that have entered enemy vehicle

### ISSUE THREAD

**Issue by Bqr1s** [SmashPhil/Vehicle-Framework#173]
**Is your feature request related to a problem? Please describe.**
There is a problem with enemy shuttles in SaveOurShip 2 mod. Player pawns can enter enemy shuttle and player will lose control over those pawns. Until vehicle is claimable, which can happen a while later, so it could be a problem for the player.

**Describe the solution you'd like**
Currently I've tested this harmony patch to be working: https://github.com/KentHaeger/SaveOurShip2/pull/28/files
So, while "enemy vehicles" is not some fully supported feature, I suggest handling this small issue on the framework side. In the patch above, the solution was chosen because of less intrusive Harmony patch. More proper solution looks like player pawns shouldn't be allowed to enter enemy vehicle, right?

**Comment by SmashPhil** [comment]
This will not be a feature in Vehicle Framework.  Claiming vehicles in general has huge implications on game balance, and to do so by just entering them would leave this mechanic open for abuse.  

Save Our Ship 2 is free to implement patches based on the needs of their ship to ship combat, but such a thing won't be considered until I've implemented vehicle raiders.  And even then, it will likely not be implemented in this fashion.
