### ISSUE TITLE
Unable to load down enemy pawn into vehicle

### ISSUE THREAD

**Issue by Channels1** [SmashPhil/Vehicle-Framework#174]
I have simple warrants mod I just down the target, but reform the caravan with the pawn selected the car doesn't move on the map.

1. Go onto world map
2. Click on reform car caravan
3. Select colonist pawns for driver, shotgun, etc(As well as items I had with them)
4. Select the down prisoner pawn.
5. Press accepts
6. See Error

.

**Additional context**
Alternatively, I tried another method by going into devmode, instant teleporting to colony, then making a car caravan at base, but they loaded everything else but the prisoner

**Comment by SmashPhil** [comment]
Please follow the bug report instructions, I need your full log.
