### ISSUE TITLE
CompUpgradeTree.Validatelisters NRE with SaveOurShip 2

### ISSUE THREAD

**Issue by Bqr1s** [SmashPhil/Vehicle-Framework#175]
**Describe the bug**
Map can be null when CompUpgradeTree.Validatelisters is called in Save Our Ship 2 with shuttles that travel between ships.

**To Reproduce**
1. Have a ship with shuttle and pilot inside shuttle
2. Start ship battle
3. Send shuttle to strafe mission

**Additional context**
[Player - Copy (4).zip](https://github.com/user-attachments/files/16311275/Player.-.Copy.4.zip)

**Comment by SmashPhil** [comment]
Fixed in the next patch
