### ISSUE TITLE
map wont load properly when using a combat vehicle to raid a npc settlement

### ISSUE THREAD

**Issue by Le-Khuong** [SmashPhil/Vehicle-Framework#176]
**Describe the bug**
so when i use bulldog to raid a base onn multiplayer server, the map took me 5 min to load and ended up not loading properly. When i reload the game, that settlement disappear and my caravan gone 
**To Reproduce**
send the bulldog to enemy npc settlement for raid

please note that bulldog is tier 2 vehicle from vanilla vehicle expanded mod 
![Screenshot_2024-07-23_at_3 00 06_PM](https://github.com/user-attachments/assets/e9ae47d7-2f97-4b85-8f66-588e9e3667fb)
![Screenshot_2024-07-23_at_3 07 59_PM](https://github.com/user-attachments/assets/0d6e301f-6917-41b3-9f6e-6217d187e6f0)

**Comment by SmashPhil** [comment]
Please follow the bug report instructions, I need the full log regardless if you think there are errors in them.

**Comment by Le-Khuong** [comment]
Hey, sorry for late respond. Im just ale to recreate that bug using the same method and it return those warning:
![Screenshot 2024-08-11 at 8 04 14 PM](https://github.com/user-attachments/assets/1d5cbb3d-b24d-4d6f-9a57-98119f922f1a)

i believe it's a mod conflict with rimworld toghether

**Comment by Le-Khuong** [comment]
^^^


> Please follow the bug report instructions, I need the full log regardless if you think there are errors in them.
