### ISSUE TITLE
Vehicle-Framework Causing Temprature&Weather Lock

### ISSUE THREAD

**Issue by FelixZSC** [SmashPhil/Vehicle-Framework#177]
Loading Vehicle-Framework causes temperature lock to -5 °C and heavy snow. 

1. Just load Vehicle-Framework

**Screenshots**
![20240727205816_1](https://github.com/user-attachments/assets/ab144fd9-dc56-4921-9393-a92c61504d39)
![20240727205821_1](https://github.com/user-attachments/assets/13233bcd-da0a-495c-a260-ca23c087dd08)
[VF_Bug.txt](https://github.com/user-attachments/files/16400251/VF_Bug.txt)

**Additional context**
I've attached Debug log and screenshots. After I encountered the bug, I went through all mods. At the end, even loading only Harmony+Core+Vehicle-Framework causes this problem. Please let me know if there are other details I can provide. Thanks!

**Comment by SmashPhil** [comment]
That's not the full log, I can't see any of VF's logs when the game boots up which means I can't look at your current version.

In any case, your screenshot shows that you've enabled one of my unit tests which have been disabled from view for players in the last update, and will have completely disabled loading in the next patch on Release builds.  Go into your config folder and locate `SmashTools.xml` and delete it.  That will reset the unit test menu, freeing you from permanent weather.

**Comment by SmashPhil** [comment]
let me know when you've done this and I'll close the issue.
