### ISSUE TITLE
VehicleWorldObjectsHolder accessed during load before it was initialized

### ISSUE THREAD

**Issue by Bqr1s** [SmashPhil/Vehicle-Framework#178]
In WorldHandling.AllAerialVehicles_AliveOrDead
Argument has "__result" name, which is reserved in Harmony:
https://github.com/SmashPhil/Vehicle-Framework/blob/fcb627f67cba95d0c57b34a9e5e7ace381b6863d/Source/Vehicles/Harmony/PatchCategories/WorldHandling.cs#L203

Reason for harmony-patching:
In unusual case when pawn finder is used during game load, calling this function causes NRE:
https://gist.github.com/HugsLibRecordKeeper/b70cfad973d7478c5979a501578206c3#file-output_log-txt-L3993

The least fix is to rename argument. Or, ideally, check for nulls.

**Comment by SmashPhil** [comment]
> In WorldHandling.AllAerialVehicles_AliveOrDead Argument has "__result" name, which is reserved in Harmony:
> The least fix is to rename argument. Or, ideally, check for nulls.

? That is a harmony patch, renaming the argument would break the patch.  The thing throwing the NRE there would probably be the world objects holder singleton.  Based on your logs that's very likely what's happening.

**Comment by SmashPhil** [comment]
@Bqr1s  Would be good to more insight as to what bug you're reporting, cause I'm not entirely sure.  Without a response I'll be forced to close the ticket.

**Comment by Bqr1s** [comment]
The issue happened in save our ship mod, where one of mod's buildings, Archotech spore, accesses pawn lister here:
https://github.com/KentHaeger/SaveOurShip2/blob/2807b5c4ce3fb6dec2f1dc0c582d48b58ce16c4b/Source/1.5/Comp/CompBuildingConsciousness.cs#L57
That eventually reaches AllAerialVehicles_AliveOrDead for shuttle in transit, and that causes NRE.

Btw, that is not the only mod causing that NRE. VFE Empire causes similar NRE too, it is here in log:
https://gist.github.com/HugsLibRecordKeeper/b70cfad973d7478c5979a501578206c3#file-output_log-txt-L3899

**Comment by SmashPhil** [comment]
Oh, that has nothing to do with the argument.  That method you're pointing out is a harmony patch, what it's doing is appending pawns inside aerial vehicles to the return value of that static getter.  The reason for the NRE would have to be the VehicleWorldObjectsHolder singleton being null at the time of access, probably too early considering it's in a scribe method.

I'll look into it.
