### ISSUE TITLE
Vehicle Framework and Camera+ compatibility issue.

### ISSUE THREAD

**Issue by LuGaNeKiT** [SmashPhil/Vehicle-Framework#180]
_English is not my native language, followed by machine translation._

   When these mods are activated, the display of prohibited items/blocks breaks. If one of the specified mods is deleted, the vanilla display of prohibited items/blocks is returned. There was no such incompatibility before the Vehicle Framework v1.5.1700 update.

   I hope for a solution to this incompatibility. :)
![20240803111138_1](https://github.com/user-attachments/assets/ecefa113-bfb3-4ab4-898c-f3cf4dc03d3f)
![20240803111807_1](https://github.com/user-attachments/assets/222286cd-5e55-4a64-8ed8-79bf6b64ebe8)
![20240803111516_1](https://github.com/user-attachments/assets/bca60c15-9d48-4e98-9b0d-9bcd80258a0b)
![20240803111733_1](https://github.com/user-attachments/assets/f140ecb2-7ba7-485f-bbe6-b95b372ea657)

**Comment by SmashPhil** [comment]
This is known, a fix is being worked on and will be out shortly

**Comment by LuGaNeKiT** [comment]
Thanks for the mod and promptness)

**Comment by SmashPhil** [comment]
Fixed in 1.5.1701
