### ISSUE TITLE
[Compatibility bug] With Vanilla classical, RJW Brothel colony, Caravans can clean, and probably any other mod might have a problem that adds timed actions on world map.

### ISSUE THREAD

**Issue by Raxon93** [SmashPhil/Vehicle-Framework#199]
**Bug description**

1. 
With Vehicle framework installed, and using any vehicle mod, all vehicle caravans will be unable to whore. Be it land based, Air, or Water.
Does not give an error log.
Game just gives "Your caravan started whoring at [Faction Base Name] "
And  instantly after "Your caravan has stopped whoring at [Faction Base Name] "
So no pimp rides i am afraid.
Only horses.

2.
Also , the road building from Vanilla classical also bugs out.
The icons dissapear but no road building happens.

3.
For caravans can clean, The clean icon simply does not appear when using a any vehicle caravan. Which is sad since its the only way you could clean up oceans near your colony.

**To Reproduce**

1.
Have Vehicle Framework

Have any Vehicle mod

Have Rjw

Have Rjw Brothel

Designate prostitute in Brothel tab

Designa prostitue in work tab

Have any vehicle

Make any vehicle caravan

Go to other friendly faction base on world map

Click start whoring on world map

!!!Task starts and stops immediately!!! (Screenshot)

2.
Have Vehicle Framework

Have any Vehicle mod

Have Vanilla Classical

Have Road Building Researched

Have any Vehicle

Make any vehicle caravan

Try to build road on world map

!!!Road building buttons dissapear as if they have started building the road but no Road building happens.!!!

3.
Have Vehicle Framework

Have any Vehicle mod

Have Caravans Can Clean

Have any Vehicle

Make any Vehicle Caravan

!!!Start clean button is not visible on world map!!! (it should be visible regardless of pollution level. If there is no pollution then greyed out.

**Extra Info**
Other mods with time based actions on the world map might also have a problem
How ever the road building from rimroads, and all related ancestors work fine.

![Screenshot 2024-10-15 202536](https://github.com/user-attachments/assets/43c90a2e-7828-408d-9dd3-900fb799eb4a)

**Comment by SmashPhil** [comment]
Yea... sorry but this is not something I would add compatibility for.  If the mod authors of RJW reach out and have proposed changes on my end then I can look into it but that's about as far as I'm willing to go.  If you have bugs to report separate from RJW compatibility then make a separate ticket for those
