### ISSUE TITLE
Merge Caravans produce normal Caravan

### ISSUE THREAD

**Issue by MrHydralisk** [SmashPhil/Vehicle-Framework#89]
**Describe the bug**
When VehicleCaravan and other normal Caravan merging it always add pawns to the one with the most pawns in it. So when merging small VehicleCaravan with bigger Caravan, then result will be just a Caravan that will have useless vehicle in it.

**To Reproduce**
1. Make VehicleCaravan of _n_ pawns and Caravan of _m_ pawns, where m > n.
2. Try merge both.
3. Get normal Caravan as result with unusable vehicle in it.

**Possible Solution**
Patch for CaravanMergeUtility:
[Patch CaravanMergeUtility.txt](https://github.com/SmashPhil/Vehicle-Framework/files/12338073/Patch.CaravanMergeUtility.txt)

**Comment by SmashPhil** [comment]
Fixed on unstable, will be out in the next patch.
