### ISSUE TITLE
Rails and trains

### ISSUE THREAD

**Issue by MrHydralisk** [SmashPhil/Vehicle-Framework#93]
**New Content**
Any plans for train vehicle type, that can operate and move only by rails (on world and colony maps)?

Trains could be a good solution for fast moving of tons of items between colony and other places connected by railroad, which can be built by player (like additional road layer). Trains speed itself not suffering from outside terrain, due to rails. Also they could have way longer acceleration and deceleration till higher speed.

Movement by rails on world map shouldn't have much issues, but movement by rails on colony map can be difficult to implement, if we allow rails to have turns. Straight 90 turn might be a rough turn for a train, so could make a custom rail for turns (like 5x5 size for example).

Since making moving train with freight wagons or any wagons would be probably a hard thing to pull off, so just locomotive vehicle would be good enough.

No need to think about types of rails or trains, since it framework, as long as it easy to mod on top.

Just a bit niche idea for far future tho, since you busy rn with main things of VF.

**Comment by SmashPhil** [comment]
Not at this time, but I know someone who does want to add them.  The issue isn't rail based pathing, it's connected vehicles and how those would move / render.

**Comment by MrHydralisk** [comment]
Figured that connected vehicles option might also unlock possibilities for making tow artillery, trailer, field kitchens and etc. Including towing damaged vehicles.

Some additional thoughts on how connected vehicle could look like (red pathing circles for 90 turns and blue for 45):

https://github.com/SmashPhil/Vehicle-Framework/assets/113328125/8e98623e-fc87-4879-9225-a8be9649607f

There no collision between car and trailer, but it stopping car from rotating more than 90 degree at a time. Once car "decided" on what next tile it will move (1 at a time in 5 directions) then it send pathing circles to trailer. Animation of trailer following car rotation starting from closest circe to it middle point. Trailer getting enough speed to being able to reach cirlce at same moment as car reach next tile. 

Min distance of each circle depends on distance between trailer hitch and trailer middle point. Following circles will be in similar to shown shape, but will change it amount depending on car and trailer size. It will overlap sometimes, but layering south vehicle on top of north one should be sufficient.

Not sure if this will help at all, but just some thoughts.
