### ISSUE TITLE
Directional Propeller/VTOL Takeoff

### ISSUE THREAD

**Issue by MrHydralisk** [SmashPhil/Vehicle-Framework#97]
**Feature request related to a problem**
So from my own experience with framework and what I asked from Oskar, it seems like in current state Helicopter type vehicles lack any usage for north and south face textures (n/s), cause PropellerTakeoff in most cases will use one east face texture for flying to either of  west or east of the map. Thus making no reasons for modders to make any texture except the one facing east, except for the short moment between building a vehicle facing north or south before it first take off. After any landing vehicle will get faced sideways, without any ability to rotate it. 

I know it using almost mandotory parameter of locked direction for takeoff "forcedRotation" from VVE examples. Even if we consider that all VTOLs meant to move sideways and never need for n/s face textures, then Graphic_Vehicle will throw some exceptions, if there is no n/s tex of vehicle.

So it like a stalemate situation, when you need to make all 3 directional textures, even tho 2 of them would be almost never used for VTOL, while making only 1 actually used one will cause other exceptions.

**Solution**
Ideally would be nice to have a version of DirectionalTakeoff from planes type vehicles for VTOL ones. Current takeoff for them already having animation for directional horizontal launch/landing, so maybe addition of settings for vertical set of animations like for planes could be enough.

**Alternative**
A bit experimental. Considering that air vehicles will be used in combat to some degree in future, then it maybe could be done one other way similar to how ground vehicles leave map as vehicle caravan.  Letting vehicle to first take off near the current spot and then move by the direction of world map target to the local map boarder. Landig will just work in opposite order. This would give a better caravan like moving out/in looks. This would require pathing/hovering to some degree, which you prob developing for combat usage.

**Simple alternative**
Since it could be hard to make, so adjusting graphics class to allow option for only east side texture vehicles or rotation of vehicles after landing animation might be a temporary, but simpler alternatives.

Overall don't take it too serious, that's just a thoughts on lack of usage for some textures for VTOL type and  how it can be changed. Thx for the awesome work on adding vehicles into the game.

**Comment by SmashPhil** [comment]
The plan is allow vehicles to land in other rotations, despite being locked to that specific landing rotation.  There's nothing stopping people from making directional takeoffs / landing animations, it's just that the VVE ones I specifically made for horizontal takeoff & landing only, as the vertical ones don't look great.  However, I can at least let the vehicle rotate upon landing so the orientation when 'parked' isn't locked just to east / west.

**Comment by MrHydralisk** [comment]
Ye, that would be nice, thx.

**Comment by SmashPhil** [comment]
Rotational landing is implemented in the next patch.  Animations will still be locked if defined with a forced rotation, but the vehicle will reorient upon landing.
