### ISSUE TITLE
Vehicle Carriers

### ISSUE THREAD

**Issue by MrHydralisk** [SmashPhil/Vehicle-Framework#98]
**New Content**
Just an idea. Not sure, if it planned for future, but currently we can't really load one vehicle into another bigger vehicle, even tho cargo weight/size realistically could allow it. Or maybe it already a thing, but I just didn't figure it out, then sorry just in case.

Allowing carrying vehicles in cargo or same way as VehicleRole work will open a possibilities for transport aviation, aircraft carriers, amphibious landing crafts and some other unique vehicles.

Storing/Deploying vehicles could be done simple way with same way how pawn enter and leave vehicle during it being stationary on local map.

Other way is to allow to deploy vehicles while carrier on world map. Either deploying vehicle only and then manually split few pawns from carrier to drive it, or using similar menu like pawns tab, where you can move carried vehicle from carrier and then move crew in it same way.

**Comment by MrHydralisk** [comment]
While was writing this idea, I found a bug with pawns tab, will post it soon once figure out reproduce way.

**Comment by MrHydralisk** [comment]
This bug was found #99

**Comment by SmashPhil** [comment]
Probably won't happen any time soon but it has been requested quite a few times.  Gonna close the card as it's already on my radar
